apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: demo-app
  namespace: default
spec:
  owner:
    projectName: default

  componentType: deployment/web-service

  parameters:
    replicas: 2
    port: 8080
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

  addons:
    - name: persistent-volume
      instanceName: data-storage
      config:
        volumeName: app-data
        mountPath: /var/data
        containerName: app
        size: "20Gi"
        storageClass: "fast"
    - name: emptydir-volume
      instanceName: cache
      config:
        volumeName: cache-vol
        mounts:
          - containerName: app
            mountPath: /tmp/cache
            readOnly: false
    - name: emptydir-volume
      instanceName: workspace
      config:
        volumeName: workspace-vol
        mounts:
          - containerName: app
            mountPath: /tmp/work
            readOnly: false
        medium: ""
        sizeLimit: 1Gi
