apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: demo-app-workload
  namespace: default
spec:
  owner:
    projectName: default
    componentName: demo-app

  containers:
    app:
      image: "nginx:1.25-alpine"
