apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: openchoreo-gitops
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/VajiraPrabuddhaka/openchoreo-gitops-demo
  ref:
    branch: main